{% set version = "4.3.2" %}

package:
  name: pcraster
  version: {{ version }}


source:
  url: http://pcraster.geo.uu.nl/pcraster/packages/src/pcraster-{{ version }}.tar.bz2
  sha256: 3ac7d3186f4ba876a5a8e8d8bf10b109bdc7b5b33d84d26bab0948f29deac2a7


build:
  number: 0
  skip: true  # [py2k]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}         # [linux]
    - {{ cdt('mesa-dri-drivers') }}         # [linux]
    - {{ cdt('libselinux') }}               # [linux]
    - {{ cdt('libxdamage') }}               # [linux]
    - {{ cdt('libxxf86vm') }}               # [linux]
    - cmake >=3.15
    - ninja
    - make                                  # [win]

  host:
    - xorg-libxfixes                        # [linux]
    - boost-cpp
    - xerces-c
    - qt
    - ncurses                               # [not win]
    - libgdal
    - python
    - numpy
    - vs2015_runtime                        # [win]
    - libglu                                # [linux]

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - boost-cpp
    - libgdal
    - ncurses                               # [not win]
    - vs2015_runtime                        # [win]
    - libglu                                # [linux]


test:
  imports:
    - pcraster
  commands:
    - asc2map
    - col2map
    - legend
    - map2asc
    - map2col
    - mapattr
    - oldcalc
    - pcrcalc
    - resample
    - table


about:
  home: http://www.pcraster.eu
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Environmental modelling software.
  description: |
    PCRaster is a collection of tools and software libraries tailored to the
    construction of spatio-temporal environmental models. Application domains
    are amongst others hydrology (rainfall-runoff, global water balance,
    groundwater (with Modflow)), ecology, or land use change.
    PCRaster includes a rich set of spatial operations for manipulating and
    analysing raster maps. A Python framework supports Monte Carlo simulations
    and data assimilation (Ensemble Kalman Filter and Particle Filter). The
    Aguila tool allows for the interactive visualisation of stochastic spatio-
    temporal data.
  doc_url: https://pcraster.geo.uu.nl/support/documentation/
  dev_url: https://github.com/pcraster/pcraster


extra:
  recipe-maintainers:
    - OliverSchmitz
    - kordejong
